# Node configuration
nodes:
  - id: 1
    address: "node1:8080"
  - id: 2
    address: "node2:8080"
  - id: 3
    address: "node3:8080"

# Replication settings
replication_factor: 2

# Raft consensus settings
raft:
  election_timeout: "1s"
  heartbeat_timeout: "500ms"
  snapshot_threshold: 1000